# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GEEA
email: contato@raulhc.cc
description: > #
  Grupo de Estudo de Eletrônica e Arduino
baseurl: "/GEEA/" # the subpath of your site, e.g. /blog
url: "http://raulhackerclub.github.io/GEEA/" # the base hostname & protocol for your site
twitter_username: raulhackerclub
github_username:  raulhackerclub

# Build settings
markdown: kramdown
